global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerting_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "orchestrators-v2"
    metrics_path: /metrics
    static_configs:
      - targets: ["orchestrators-v2:8088"]
